config_version = 14

[audio]
enable_overdrive = true

[bar]
order = [ "main" ]

    [bar.default]
    background_opacity = 0.0
    capsule = true
    capsule_border = "primary"
    capsule_fill = "surface"
    capsule_opacity = 0.75
    capsule_padding = 6
    capsule_radius = 4.0
    capsule_thickness = 0.62729999999999997
    center = [ "clock" ]
    color = "on_surface"
    end = [
        "notifications",
        "clipboard",
        "network",
        "volume",
        "system-monitor-btn",
        "tray",
        "nightlight",
        "settings",
        "screen-time-btn",
        "weather",
        "session"
    ]
    font_scale = 0.94999999999999996
    font_weight = 400
    hover_highlight = true
    margin_edge = 0
    margin_ends = 0
    margin_opposite_edge = 0
    padding = 14
    position = "top"
    radius = 4
    radius_bottom_left = 4
    radius_bottom_right = 4
    radius_top_left = 4
    radius_top_right = 4
    scale = 1.1499999999999999
    shadow = false
    start = [ "workspaces", "active_window", "media" ]
    thickness = 44
    widget_spacing = 8

[calendar]
enabled = true

[control_center]
width = 730

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
active_monitor_only = true
layer = "overlay"
reserve_space = false
show_dots = true

[location]
address = "Kathmandu"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@FALLBACK", "lockscreen-login-box@DP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = false
force = false

[notification]
scale = 1.2000000104308128

[plugin_settings."noctalia/notes"]
panel_open_near_click = true
panel_placement = "attached"

[plugins]
auto_update = "official"
enabled = [ "felipeartur/ai-usagebar", "noctalia/bitwarden", "noctalia/wallpaper_depth", "noctalia/notes" ]

[shell]
corner_radius_scale = 0.0
font_family = "JetBrains Mono SemiBold"
screen_time_enabled = true

    [shell.launcher]
    app_grid = true
    compact = true
    show_app_actions = true

    [shell.panel]
    clipboard_position = "auto"
    floating_layer = "top"
    list_item_background = true
    polkit_placement = "attached"
    transparency_mode = "glass"

[theme]
builtin = "Catppuccin"
community_palette = "Ayu Green"
custom_palette = "CatppuccinMocha"
mode = "dark"
source = "custom"
wallpaper_scheme = "soft"

[wallpaper]
directory = "/home/kneeraazon/.wallpapers/Edna-RanchoCucamonga"
directory_dark = "/home/kneeraazon/.wallpapers"
directory_light = "/home/kneeraazon/.wallpapers/Edna-RanchoCucamonga"

    [wallpaper.default]
    path = "/home/kneeraazon/.wallpapers/wally.jpg"

    [wallpaper.last]
    path = "/home/kneeraazon/.wallpapers/wally.jpg"

    [wallpaper.monitors.DP-2]
    path = "/home/kneeraazon/.wallpapers/wally.jpg"

[widget.active_window]
color = "on_surface_variant"

[widget.clipboard]
icon_color = "secondary"

[widget.clock]
color = "primary"
font_scale = 1.0
format = "{:%a, %d %b | %H:%M:%S}"

[widget.media]
hide_when_no_media = true
icon_color = "primary"

[widget.network]
icon_color = "secondary"
show_label = false

[widget.nightlight]
glyph = "moon-off"
icon_color = "tertiary"
tooltip = "Night Light (on/off)"
type = "custom_button"

    [widget.nightlight.actions]
    left = "exec /home/kneeraazon/.config/hypr/scripts/nightlight-toggle.sh"

[widget.notifications]
icon_color = "tertiary"

[widget.screen-time-btn]
glyph = "hourglass"
icon_color = "secondary"
tooltip = "Screen Time"
type = "custom_button"

    [widget.screen-time-btn.actions]
    left = "panel-open control-center screen-time"

[widget.session]
capsule_padding = 10
icon_color = "primary"

[widget.settings]
icon_color = "secondary"

[widget.system-monitor-btn]
glyph = "cpu"
icon_color = "primary"
tooltip = "CPU / GPU / RAM"
type = "custom_button"

    [widget.system-monitor-btn.actions]
    left = "panel-open control-center system"

[widget.volume]
icon_color = "tertiary"
show_label = false

[widget.weather]
icon_color = "secondary"
show_condition = false
show_temperature = true