config_version = 14

[bar]
order = [ "kneeraazon" ]

    [bar.kneeraazon]
    border = "primary"
    border_width = 2.0
    capsule = true
    capsule_border = "#cba6f799"
    capsule_fill = "primary"
    capsule_opacity = 0.0
    capsule_padding = 6
    capsule_radius = 4
    capsule_thickness = 0.81
    contact_shadow = true
    end = [
        "tmelik/system-monitor:summary",
        "notifications",
        "clipboard",
        "volume",
        "network",
        "tray",
        "bluetooth",
        "brightness",
        "battery",
        "nightlight",
        "control-center",
        "session",
        "active_window"
    ]
    font_family = "JetBrains Mono"
    font_scale = 0.92999998666346073
    font_weight = 600
    hover_highlight = false
    icon_color = "surface"
    margin_edge = 0
    margin_ends = 0
    margin_opposite_edge = 0
    padding = 4
    radius = 0
    scale = 1.1500000096857548
    start = [ "launcher", "wallpaper", "workspaces", "media" ]
    thickness = 42
    widget_spacing = 16

[control_center.calendar]
show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[location]
address = "Kathmandu, Nepal"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@FALLBACK", "lockscreen-login-box@DP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-2"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
temperature_night = 5500

[plugin_settings."noctalia/bitwarden"]
unlock_placement = "attached"

[plugin_settings."noctalia/notes"]
panel_open_near_click = true
panel_placement = "attached"

[plugins]
auto_update = "none"
enabled = [
    "felipeartur/ai-usagebar",
    "noctalia/bitwarden",
    "noctalia/wallpaper_depth",
    "noctalia/notes",
    "cleboost/zed-provider",
    "gustav0ar/wireview-pro-ii",
    "umedbazarov/webapp-maker",
    "notfinaldev/web-search",
    "yocraft/web-launcher",
    "kavya-nama/wallpaper-switcher",
    "noctalia/wallhaven",
    "noctalia/mpvpaper",
    "neuro/upbeat",
    "noctalia/umbriel-companion",
    "aristides/udiskie",
    "noctalia/translator",
    "nightwatch75/topgrade-wrapper",
    "noctalia/timer",
    "tordex/system-updater",
    "jamesfeeder/special-workspaces",
    "tmelik/system-monitor",
    "arrifat346afs/systempulse",
    "redxtech/super-productivity",
    "cleboost/ssh-launcher",
    "notfinaldev/spotify",
    "joshuaslate/shelly",
    "alexander/screen-toolkit",
    "whyoolw/sharednd",
    "weinguyen/shell-command",
    "nilsonlinux/rss-notifier",
    "rylos/remmina",
    "yocraft/qrcode",
    "harveywuk/pulsar-mouse",
    "weinguyen/procmon",
    "radimous/prismlauncher-instances",
    "rxtsel/portctl",
    "thepunkoff/pomodoro",
    "decksters-lab/palette-creator",
    "davemhammer/obsidian",
    "emrtnn/pass",
    "icefish/phone-connect",
    "icefish/phone-operate",
    "davemhammer/opnsense",
    "wy3z/opencodex-bar",
    "weinguyen/opencode-companion",
    "teagar/omniroute-quota",
    "fel/ocr",
    "neyfua/obs-integration",
    "tordex/nvtop",
    "goodroot/noctwhspr",
    "weinguyen/9router-control",
    "yuuto/arch-updater",
    "0lucasmatheus/awwwall",
    "blackbartblues/audio-switcher",
    "yugaaank/better-clock",
    "nirvam/bitdjinn",
    "noctalia/bongocat",
    "dunarand/bookmarks",
    "dragged/cider",
    "dotnetrob/cat",
    "kjvdven/case-convert",
    "yuuto/calculator",
    "lowcache/claude-companion",
    "levi/warp",
    "salemsayed/codexbar-meter",
    "oldirtty/color_picker",
    "yocraft/desktop-launcher",
    "raycursive/discord-voice",
    "nightwatch75/dns-switcher",
    "liamwh/emoji-picker",
    "apex077/eyecare",
    "nightwatch75/file-search",
    "tphilippot/git_companion",
    "alexmnrs/github-activity",
    "raycursive/github-prs",
    "maddingo/hypr-layout-switcher",
    "pozzoo/hassio",
    "noctalia/world_clock",
    "noctalia/screen_recorder",
    "noctalia/kaomoji"
]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
corner_radius_scale = 0.5000000074505806
font_family = "DejaVu Sans"
panel_anchor_bar = "kneeraazon"

    [shell.launcher]
    app_grid = true
    compact = true
    show_app_actions = true

    [shell.panel]
    clipboard_placement = "attached"
    floating_layer = "top"
    launcher_position = "top_left"
    polkit_placement = "attached"
    transparency_mode = "glass"

[theme]
builtin = "Catppuccin"
community_palette = "Catppuccin Frappe Blue"
custom_palette = "CatppuccinMocha"
mode = "auto"
shell_mode = "dark"
source = "builtin"

    [theme.templates]
    builtin_ids = []

[wallpaper]
directory = "/home/kneeraazon/.wallpapers"
transition_on_startup = true

    [wallpaper.automation]
    interval_seconds = 1794
    order = "alphabetical"

    [wallpaper.default]
    path = "/home/kneeraazon/.wallpapers/Wallpaper22.png"

    [wallpaper.last]
    path = "/home/kneeraazon/.wallpapers/Wallpaper22.png"

    [wallpaper.monitors.DP-2]
    path = "/home/kneeraazon/.wallpapers/Wallpaper22.png"

    [[wallpaper.favorite]]
    builtin_palette = "Catppuccin"
    palette_source = "builtin"
    path = "color:#6913D1"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/thumb-1920-1356859.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/1356855.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/1360645.jpeg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/wally.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/wp15585667.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/wp8149239.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/wp7616371.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/25755707.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/Wallpaper22.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/city-building-near-water-shot-from-bars-bridge.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/gruvbox_dypuzktoewk71.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/gruvbox_fkaz52mvm3l71.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/kneeraazon/.wallpapers/a_fog_over_water_with_a_black_background.jpg"
    theme_mode = "auto"

[widget.active_window]
color = "on_surface_variant"
enabled = true

[widget.battery]
enabled = true

[widget.brightness]
enabled = true

[widget.clipboard]
capsule = true
icon_color = "#FFFFFF"

[widget.clock]
capsule = true
capsule_padding = 12
font_family = "JetBrains Mono ExtraBold"
font_scale = 1.0
font_weight = 700
format = "{:%a, %d %b | %H:%M:%S}"

[widget.control-center]
capsule = true
font_weight = 700
icon_color = "#03FD8B"

[widget.launcher]
capsule = true
capsule_padding = 13
color = "surface"
enabled = true
icon_color = "surface"

[widget.media]
anchor = true
capsule = true
capsule_padding = 7
color = "secondary"
font_weight = 400
hide_when_no_media = true
icon_color = "on_surface"
scale = 1.1000000000000001
show_progress = true
title_scroll = "always"

[widget.network]
capsule = true
icon_color = "#00E5FF"
show_label = false

[widget.nightlight]
icon_color = "tertiary"

    [widget.nightlight.actions]
    left = "nightlight-force-toggle"

[widget.notifications]
capsule = true
icon_color = "#F66409"

[widget.screen-time-btn]
glyph = "hourglass"
icon_color = "secondary"
tooltip = "Screen Time"
type = "custom_button"

    [widget.screen-time-btn.actions]
    left = "panel-open control-center screen-time"

[widget.session]
capsule = true
capsule_padding = 10
icon_color = "#F90540"

[widget.settings]
icon_color = "secondary"

[widget."tmelik/system-monitor:summary"]
show_cpu_temperature = false
show_cpu_usage = false
show_disk = false
show_download = true
show_gpu_temperature = "off"
show_gpu_usage = "off"
show_gpu_vram = "off"
show_ram = false
show_swap = false
show_upload = true

[widget.tray]
capsule = true

[widget.volume]
capsule = true
icon_color = "#FF4C00"
show_label = false

[widget.wallpaper]
enabled = true

[widget.weather]
icon_color = "secondary"
show_condition = false
show_temperature = true

[widget.workspaces]
capsule = true
capsule_padding = 0
color = "surface"
empty_color = "primary"
focused_color = "#06C1F9"
font_scale = 1.2
hide_when_empty = true
icon_color = "surface"
label_source = "name"
occupied_color = "#F4910A"
scale = 1.3
show_all_outputs = true
urgent_color = "#F20941"