# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_THEME,catppuccin-mocha-blue-cursors
envd = HYPRCURSOR_SIZE,24
envd = XCURSOR_THEME,catppuccin-mocha-blue-cursors
envd = XCURSOR_SIZE,24
envd = QT_CURSOR_SIZE,24
envd = COLORTERM,truecolor
envd = GTK_THEME,catppuccin-mocha-blue-standard+default
